version: "3.8"

services:
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UtpMusic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - utp_network

  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-config.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - utp_network

networks:
  utp_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
