spring:
  application:
    name: music
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/UtpMusic
    username: postgres
    password: postgres

server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
    io:
      r2dbc: DEBUG

